sudo: false

language: node_js

node_js:
  - node

cache: npm

install:
  - npm ci

script:
  - npm run lint
  - npm run build
  - npm run test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  target_branch: build
  on:
    branch: master

notifications:
  email: false